pool:
  name: Azure Pipelines

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - nstck-api
      - azure-pipelines-nstck-api

variables:
  BuildConfiguration: $(Pipeline.Workspace)/.build-configuration

steps:
  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      workingDirectory: nstck-api
      command: restore
      projects: nstck-api/nStck.API.csproj

  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      workingDirectory: nstck-api

  - task: DotNetCoreCLI@2
    displayName: "dotnet publish"
    inputs:
      workingDirectory: nstck-api
      command: publish
      arguments: "--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "Publish API Artifact"
    inputs:
      ArtifactName: API
