---

parameters:
  - name: app_name
    type: string

steps:
  - bash: |
      export GITLAB_PYPI_HOST="$(GITLAB-PYPI-HOST)"
      export GITLAB_PYPI_USERNAME="$(GITLAB-PYPI-USERNAME)"
      export GITLAB_PYPI_PASSWORD="$(GITLAB-PYPI-PASSWORD)"
      ./scripts/pypi_credentials.sh ${{parameters.app_name}}
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: Prepare GitLab credentials
