pool:
  name: Azure Pipelines

trigger: none

stages:
- stage: A
  jobs:
  - job: Build
    steps:
    - bash: echo "Imagine this is our build output"
  - job: Tests
    steps:
    - bash: echo "This can be our Unit Tests execution output"
    - bash: echo "This can be our Integration Tests execution output"

- stage: Staging
  jobs:
  
  - deployment: 'StagingDeployment'
    displayName: Staging
    environment: 'ApprovalNotRequired'
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: echo "Deploy to staging"
    

- stage: Production
  jobs:
  - deployment: 'MyDeployment2'
    displayName: MyDeployment2
    environment: 'ApprovalRequired'
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: echo "Deploy to prod"